In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

# Array creation methods


In [6]:
myArr = np.array([[1,2,3],[5,6,7]], np.int8)

In [7]:
myArr

array([[1, 2, 3],
       [5, 6, 7]], dtype=int8)

In [8]:
myArr.shape

(2, 3)

In [9]:
myArr.size


6

In [10]:
myArr[0,0]=11

In [11]:
myArr

array([[11,  2,  3],
       [ 5,  6,  7]], dtype=int8)

In [13]:
zeroArr = np.zeros((2,5))

In [14]:
oneArr = np.ones((2,2))

In [15]:
oneArr

array([[1., 1.],
       [1., 1.]])

In [16]:
arr2 = np.arange(3)

In [17]:
arr2

array([0, 1, 2])

In [19]:
lnspace = np.linspace(1,5,5)

In [20]:
lnspace

array([1., 2., 3., 4., 5.])

In [21]:
lnspace2 = np.linspace(1,5,5,np.int8)

In [24]:
lnspace2.dtype = np.int8

In [25]:
lnspace2

array([  0,   0,   0,   0,   0,   0, -16,  63,   0,   0,   0,   0,   0,
         0,   0,  64,   0,   0,   0,   0,   0,   0,   8,  64,   0,   0,
         0,   0,   0,   0,  16,  64,   0,   0,   0,   0,   0,   0,  20,
        64], dtype=int8)

In [26]:
emp = np.empty_like(arr2)  #this will create an array like arr2 */

In [27]:
emp  

array([-2025983984,         446,           0])

In [29]:
emp = np.empty((2,3))  # create array of 2,3 size with random numbers(float*/)

In [30]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
id = np.identity(5)

In [32]:
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr3 = np.arange(20)

In [34]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr3.reshape(2,10)   # 2 * 10 =20 so it could be reshaped but 1,10 or 2,3 etc can't be*/S

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [37]:
arr3.ravel()  #becomes 1D array*/

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Array Axis

In [38]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr4.T   # Transpose of array */

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr4.sum(axis = 0)  # axis 0 is y-axis just think like that for remembering and so it will sum the elements in columns / vertically*/

array([12, 15, 18])

In [43]:
arr4.sum(axis = 1)   # axis 1 is x-axis just think like that for remembering and so it will sum the elements in rows / horizontally*/

array([ 6, 15, 24])

In [44]:
for i in arr4:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [45]:
arr4.flat  #it provides  an iterator to iterate through the elements*/

In [47]:
for item in arr4.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [48]:
arr4.ndim

2

In [49]:
arr4.size

9

In [50]:
arr4.nbytes

36

**without parenthesis are attributes with parenthesis are methods**

In [57]:
one = np.array([1,2,655,76])

In [60]:
  one.argmax()    #gives index of maximum element

2

In [62]:
one.argmin()

0

In [63]:
one.sort()

In [64]:
one

array([  1,   2,  76, 655])

In [65]:
two = np.array([1,34,3,657,43])

In [66]:
two.argsort()   #this will give the indices in order to sort the elements

array([0, 2, 1, 4, 3], dtype=int64)

In [67]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr4.argmin()

0

In [70]:
arr4.argmax()

8

In [71]:
arr4.argmax(axis=0)  #maximum element in 0 or vertical axis

array([2, 2, 2], dtype=int64)

In [72]:
arr4.argmax(axis=1)  #maximum element in 01 or horizontal axis

array([2, 2, 2], dtype=int64)

In [74]:
arr4.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [75]:
arr4.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr4.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
ar1 = np.array([[1,2,3],[3,4,5],[3,43,4]])

In [81]:
ar2 = np.array([[3,45,6],[9,0,6],[0,4,6]])

In [82]:
ar1

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 3, 43,  4]])

In [83]:
ar2

array([[ 3, 45,  6],
       [ 9,  0,  6],
       [ 0,  4,  6]])

In [84]:
ar1 + ar2

array([[ 4, 47,  9],
       [12,  4, 11],
       [ 3, 47, 10]])

In [85]:
ar1 * ar2

array([[  3,  90,  18],
       [ 27,   0,  30],
       [  0, 172,  24]])

In [86]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798],
       [1.73205081, 6.55743852, 2.        ]])

In [87]:
ar1.sum(
)

68

In [88]:
ar1.min()

1

In [90]:
ar1.max()

43

In [94]:
type(np.where(ar1>5))

tuple

In [92]:
ar1

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 3, 43,  4]])

In [95]:
np.count_nonzero(ar1)

9

In [96]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [97]:
import sys

In [98]:
list = [3,5,6]

In [99]:
arr = np.array(list)

In [100]:
list

[3, 5, 6]

In [101]:
arr

array([3, 5, 6])

**storage difference between python list and numpy array**

In [104]:
sys.getsizeof(1) * len(list)

84

In [107]:
arr.nbytes

12

In [108]:
arr.itemsize * arr.size

12